[package]
name = "aurora_scholar"
version = "0.1.0"
description = "Decentralized academic publishing on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "aurora_scholar"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "0.32.1"

